#!/usr/bin/env zsh
# Everything except theme/plugins — those live in ~/.zshrc, generated by
# the stock oh-my-zsh installer and patched in place by install.sh (sed for
# ZSH_THEME/plugins, no static .zshrc checked into this repo).
# .zshenv loads for every zsh invocation (login, interactive, script), so
# interactive-only bits (options, bindkeys, aliases) are gated behind the
# check below to avoid slowing down every subshell/script.

# --- always-on: env vars, PATH ---------------------------------------------
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export LANG="en_US.UTF-8"

typeset -U path
path=("$HOME/.local/bin" $path)
export PATH

export HISTFILE="$XDG_STATE_HOME/zsh/history"
export HISTSIZE=50000
export SAVEHIST=50000
[[ -d "${HISTFILE:h}" ]] || mkdir -p "${HISTFILE:h}"

# --- machine-specific env, copied verbatim from this machine's .zshrc ------
export GOPRIVATE=github.com/Aturjadwal/*,github.com/faizauthar12/*,github.com/dbo-id/*,github.com/21strive/*
export GONOPROXY=github.com/Aturjadwal/*,github.com/faizauthar12/*,github.com/dbo-id/*,github.com/21strive/*
export GONOSUMDB=github.com/Aturjadwal/*,github.com/faizauthar12/*,github.com/dbo-id/*,github.com/21strive/*
export PATH="$PATH:$(go env GOPATH)/bin"

# Flutter path
export PATH="$PATH:$HOME/bin/flutter/bin"

# Android home path
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache
export CCACHE_DIR=~/ccache

#sccache
export SCCACHE_DIR="$HOME/.cache/sccache"
export SCCACHE_CACHE_SIZE="150G"

# Cargo
export CARGO_HOME=$HOME/.cargo
export PATH="$CARGO_HOME/bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/faizauthar/.lmstudio/bin"
# End of LM Studio CLI section

. "$HOME/.local/bin/env"
export PATH=~/.npm-global/bin:$PATH

# --- interactive-only below --------------------------------------------------
[[ $- == *i* ]] || return 0

setopt AUTO_CD EXTENDED_GLOB
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_VERIFY SHARE_HISTORY
setopt INTERACTIVE_COMMENTS
bindkey -e

alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias ..='cd ..'
alias g='git'

# thinkpad power-profile switcher via power-profiles-daemon
# see hardware/check-thinkpad-t14.sh for the raw ACPI fallback
alias pp-eco='powerprofilesctl set power-saver'
alias pp-bal='powerprofilesctl set balanced'
alias pp-perf='powerprofilesctl set performance'
