#!/usr/bin/env zsh
# Everything except theme/plugins — those live in ~/.zshrc, generated by
# the stock oh-my-zsh installer and patched in place by install.sh (sed for
# ZSH_THEME/plugins, no static .zshrc checked into this repo).
# .zshenv loads for every zsh invocation (login, interactive, script), so
# interactive-only bits (options, bindkeys, aliases) are gated behind the
# check below to avoid slowing down every subshell/script.

# --- always-on: env vars, PATH ---------------------------------------------
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export LANG="en_US.UTF-8"

typeset -U path
path=("$HOME/.local/bin" $path)
export PATH

export HISTFILE="$XDG_STATE_HOME/zsh/history"
export HISTSIZE=50000
export SAVEHIST=50000
[[ -d "${HISTFILE:h}" ]] || mkdir -p "${HISTFILE:h}"
